AWSTemplateFormatVersion: 2010-09-09
Description: Template to create a lexbot

Resources:
  LexChatBot:
    Type: Custom::LexBot
    Properties:
      ServiceToken: !GetAtt ChatBotLambda.Arn
      NamePrefix: FirstChatBot
      ShouldDelete: false

  ChatBotLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: the bucket where the code is
        S3Key: the path to the bucket
      Handler: chat-bot-application-main.handler
      Role: !GetAtt ChatBotLambdaRole.Arn
      Runtime: python2.7
      Timeout: 300

  ChatBotLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Principal:
              Service:
                - lambda.amazonaws.com
            Effect: Allow
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LogsForLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                Resource:
                    - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
                    - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*"
        - PolicyName: LexGet
          PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - lex:Get*
                  Resource: '*'
        - PolicyName: LexMutating
           PolicyDocument:
               Version: 2012-10-17
               Statement:
                   - Effect: Allow
                     Action:
                         - lex:Put*
                         - lex:Delete*
                     Resource:
                         - !Sub "arn:aws:lex:${AWS::Region}:${AWS::AccountId}:bot:${NamePrefix}*:*"
                         - !Sub "arn:aws:lex:${AWS::Region}:${AWS::AccountId}:intent:${NamePrefix}*:*"
                         - !Sub "arn:aws:lex:${AWS::Region}:${AWS::AccountId}:slottype:${NamePrefix}*:*"